import { Circle, CircleMarker, Polygon, Tooltip as LeafletTooltip } from 'react-leaflet'
import { useMapStore } from '@/store/mapStore'
import { LAYER_DEFINITIONS } from '@/constants/map'
import { scoreToHeatmapColor } from '@/utils/color'
import { generateIsochroneRings } from '@/features/map/analysis/isochroneEngine'
import type { MockNode } from '@/mock/nodes'

/**
 * Purpose
 * -------
 * Renders two related-but-distinct visualizations gated by their own
 * layer toggles: (1) walking-time isochrone rings around the currently
 * selected node — four concentric bands (5/10/15/20 min) generated by
 * analysis/isochroneEngine.ts's generateIsochroneRings(), each with a
 * distinct color/opacity and a CSS fade-in animation (see
 * `.isochrone-ring` in styles/index.css) on mount — and (2) the
 * coverage Heatmap, one colored circle per existing node sized/colored
 * by coverageScore. Grouped in one file since both are "coverage
 * visualization at a point" rather than distinct geometry sources like
 * roads/flood zones.
 *
 * Props
 * -----
 * - existingNodes: MockNode[] — needed for the heatmap and to resolve
 *   the selected node's position for the isochrone rings
 *
 * Example usage
 * -------------
 * <IsochroneLayer existingNodes={filteredNodes} /> // inside <MapContainer>
 *
 * Accessibility
 * -------------
 * N/A.
 *
 * Future ORS integration
 * -----------------------
 * See analysis/isochroneEngine.ts's doc comment — swapping the circular
 * approximation for real OpenRouteService polygons only changes what
 * `generateIsochroneRings` returns, not this rendering code (Circle
 * would become Polygon once real ring geometry exists, still reading
 * the same `color`/`fillOpacity`/`order` fields).
 */
const isochroneDefinition = LAYER_DEFINITIONS.find((layer) => layer.id === 'isochrones')!
const heatmapDefinition = LAYER_DEFINITIONS.find((layer) => layer.id === 'heatmap')!

export function IsochroneLayer({ existingNodes }: { existingNodes: MockNode[] }) {
  const zoom = useMapStore((state) => state.zoom)
  const isochronesVisible = useMapStore((state) => state.activeLayers['isochrones'])
  const isochroneOpacity = useMapStore((state) => state.layerOpacity['isochrones'])
  const heatmapVisible = useMapStore((state) => state.activeLayers['heatmap'])
  const heatmapOpacity = useMapStore((state) => state.layerOpacity['heatmap'])
  const selectedNodeId = useMapStore((state) => state.selectedNodeId)

  const selectedNode = existingNodes.find((node) => node.id === selectedNodeId)
  const showIsochrone =
    isochronesVisible &&
    selectedNode &&
    zoom >= isochroneDefinition.minZoom &&
    zoom <= isochroneDefinition.maxZoom
  const showHeatmap =
    heatmapVisible && zoom >= heatmapDefinition.minZoom && zoom <= heatmapDefinition.maxZoom

  const rings = showIsochrone ? generateIsochroneRings() : []

  return (
    <>
      {showIsochrone &&
        selectedNode &&
        rings.map((ring) => (
          <Circle
            key={ring.minutes}
            center={selectedNode.position}
            radius={ring.radiusMeters}
            pathOptions={{
              className: 'isochrone-ring',
              color: ring.color,
              weight: 1.5,
              fillColor: ring.color,
              fillOpacity: ring.fillOpacity * isochroneOpacity * 2,
            }}
          >
            <LeafletTooltip sticky>
              {ring.minutes} min walk (~{Math.round(ring.radiusMeters)}m) from {selectedNode.name}
            </LeafletTooltip>
          </Circle>
        ))}

      {showHeatmap &&
        existingNodes.map((node) => (
          <CircleMarker
            key={`heat-${node.id}`}
            center={node.position}
            radius={14}
            pathOptions={{
              stroke: false,
              fillColor: scoreToHeatmapColor(node.coverageScore),
              fillOpacity: 0.35 * heatmapOpacity,
            }}
          />
        ))}
    </>
  )
}

/** Rough Greater Accra metro boundary — placeholder for the
 *  Administrative Boundaries layer until real boundary GeoJSON exists. */
export function AdminBoundariesLayer() {
  const zoom = useMapStore((state) => state.zoom)
  const visible = useMapStore((state) => state.activeLayers['admin-boundaries'])
  const definition = LAYER_DEFINITIONS.find((layer) => layer.id === 'admin-boundaries')!

  if (!visible || zoom < definition.minZoom || zoom > definition.maxZoom) return null

  return (
    <Polygon
      positions={[
        [5.47, -0.32],
        [5.47, 0.02],
        [5.75, 0.02],
        [5.75, -0.32],
      ]}
      pathOptions={{ color: 'var(--color-neutral-400)', weight: 2, dashArray: '6 4', fill: false }}
    >
      <LeafletTooltip sticky>Greater Accra Metro (approx.)</LeafletTooltip>
    </Polygon>
  )
}
