import { useMemo } from 'react'
import { Line } from 'react-chartjs-2'
import type { ChartOptions } from 'chart.js'
import { ChartContainer } from '@/components/charts'
import { generateTrendSeries, KPI_TREND_SEEDS } from '@/mock/dashboardTrends'
import { getBaseChartOptions, getChartPalette } from './chartTheme'
import { hexToRgba } from '@/utils/color'

/**
 * Purpose
 * -------
 * Line chart of citywide coverage percentage over the last 6 months.
 * Unlike the other four charts, this one has no real historical data to
 * group — coverage % today is a single live number (statistics.ts's
 * calculateOverviewStatistics), not a time series. The trend is
 * generated by mock/dashboardTrends.ts, explicitly documented there as
 * a placeholder pending Phase 10's real coverage-snapshot history.
 *
 * Props
 * -----
 * - currentCoveragePercent: number (0–100) — the live value the series
 *   should end at, so the chart agrees with the KPI row above it
 */
export interface CoverageTrendChartProps {
  currentCoveragePercent: number
}

export function CoverageTrendChart({ currentCoveragePercent }: CoverageTrendChartProps) {
  const series = useMemo(
    () => generateTrendSeries(KPI_TREND_SEEDS.coveragePercent, currentCoveragePercent, 6, 0.05),
    [currentCoveragePercent]
  )
  const palette = useMemo(() => getChartPalette(), [])

  const data = {
    labels: series.map((point) => point.label),
    datasets: [
      {
        label: 'Coverage %',
        data: series.map((point) => Math.round(point.value * 10) / 10),
        borderColor: palette[0],
        backgroundColor: hexToRgba(palette[0]!.startsWith('#') ? palette[0]! : '#3b82f6', 0.12),
        fill: true,
        tension: 0.35,
        pointRadius: 3,
        pointBackgroundColor: palette[0],
      },
    ],
  }

  const base = getBaseChartOptions()
  const options = {
    ...base,
    plugins: { ...base.plugins, legend: { display: false } },
    scales: {
      x: base.scales?.x,
      y: { ...base.scales?.y, ticks: { ...base.scales?.y?.ticks, callback: (v: number | string) => `${v}%` } },
    },
  } as unknown as ChartOptions<'line'>

  return (
    <ChartContainer height={260}>
      <Line data={data} options={options} aria-label="Citywide coverage percentage trend" role="img" />
    </ChartContainer>
  )
}
